travis:
  secure:
    BINSTAR_TOKEN: 013dmCfNmPJSzOXoODIpegkj1/AN3RLt0UhNgRQ3Z6Dm18agtA2bCAdZg/OIDA+DMKjVGYlyWBSf4NntvPTfys/bd1R18OV8LknO2eMP4yjCPMe2cwtc4xvB+H63RHXE8DwGVgF4R1nRy77lB46IA8uhZXOxbrrRL6UHxZBKw3CjL/9c6LTIs6poBeVh5J+gvRXi+FYz0f672ueTnoYls6TUR+Pl17+1gZkc6eLL5IianyKsf+e+yhfji1iFAiw3XlQ3l2eW4aVyg3XI1A3DMKCPx0ye6JMpdQhb48E64tnI+P7zj414A07YtwMbd78QQ0pZaSjrW0GlMeEsEeclhvRyowhCLBaYO/srGD4cil+7Lq1SvVKt0cw2khpseo3+FO2YS+8pdvsIZbJvMXZjG3xyxLzXKhLyAZ5En0cStSpjBNUhXe4GclhEEf9S2DVS3EIHDk1Rguvz0G74nG5UgAxOQ16mLtr13SZu0JvgFoVtFG6D3ITUnaDLouUUDtVMXPDb9aMM+kcHqFqi3TozLKpYvD10g8YVegOLuSbJvnutIZ0Cl9KfajEPqiTFSZBiYNDyi7gP95GyYfRwBbBXaaEUcPeiK9xYcc4aKaVXDIRrg+Q+wtLaH4KcrwiSw2URtshw7vELbQ2Jx6TmnvEYR76PcevfEIr+o6Xv6ekQdt0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
